<ul class="nav">
    <?php foreach($this->menu as $menuItem): ?>
        <li class="divider-vertical"></li>
        <?php if($menuItem->hasSubmenu): ?>
            <li>
                <a href="<?php echo $menuItem->href; ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $menuItem->text; ?> <b class="caret"></b></a>
                <?php echo $menuItem->submenu ?>
            </li>
        <?php else: ?>
            <li><a href="<?php echo $menuItem->href; ?>"><?php echo $menuItem->text; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    <li class="divider-vertical"></li>
</ul>