<div class="row">
    <div class="span12">
        <h1>Startseite</h1>
        <div class="well">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta lorem nec dolor ultrices sed dapibus justo pellentesque. Ut augue est, convallis in bibendum eu, mattis eu augue. Nullam et nisl id nunc sagittis laoreet. Suspendisse vel fermentum est. Fusce blandit nulla non leo congue et dapibus purus vulputate. Nam dictum erat ac nulla venenatis aliquam. Vivamus gravida aliquam leo eu cursus. Nunc vel posuere lectus. Vivamus mauris sapien, laoreet non aliquet sit amet, consectetur fringilla velit. Donec imperdiet dictum ipsum nec aliquam. Pellentesque nulla mauris, pellentesque ac vehicula sit amet, porttitor et ante. Morbi a bibendum nisl. Donec nec euismod turpis.</p>
        </div>
    </div>
</div>
